### ISSUE TITLE
Wrong ezc exchange arithmetic

### ISSUE THREAD

**Issue by xcaptain** [deeper-chain/web3d#2]
https://github.com/deeper-chain/web3d/blob/9747f5c7569e1f26f0eee67c7065d39e0f2c3fc1/contract/EZC.sol#L1625

`dprAmount` has 18 decimals, `price` is DPR to USD exchange rate, also has 18 decimals. you can't simply multiply these 2 variables.
The right arithmetic should be:

```
uint256 usd = (dprAmount / 1000000000000000000) * price; // remove 18 decimals and exchange to usd
uint256 ezc = usd * 100; // exchange usd to ezc
```

Don't know if solidity has library like `decimal` so `dprAmount / 1000000000000000000` won't loose precision.

Some error logs:
http://blockscount-dev.deeper.network/address/0x8B88D1FF82198E78516d794879cE7FE2f04DF136/transactions
![image](https://user-images.githubusercontent.com/4054836/169341596-ebe8e072-f716-4db9-982b-b355af140d35.png)

**Comment by AmadeusGB** [comment]
fixed!
[uint256 ezcAmount = (dprAmount * price * 100) / (10 ** 18);](https://github.com/deeper-chain/web3d/commit/867582c0665753e05cd2024a01d7b6cce68fb6a2)
